### ISSUE TITLE
Checking which M-Key is glowing for rules

### ISSUE THREAD

**Issue by Svenum** [pwr-Solaar/Solaar#1493]
I am using the newest solaar version from the repo.
I like that i am now able to control the M-Keys. Is there a possibility, that i can make a rule that checks if M1 or M2 or M3 is enabled?
If I can do this, then it will be possible to create different shortcut-profiles for the G-Keys.

Example:

```
if(M1 == glowing){
   G1 = CTRL + 1
   G2 = CTRL + 2
   G3 = CTRL + 3
   G4 = CTRL + 4
   G5 = CTRL + 5
} else if(M2 == glowing){
   G1 = CTRL + ALT + 1
   G2 = CTRL + ALT + 2
   G3 = CTRL + ALT + 3
   G4 = CTRL + ALT + 4
   G5 = CTRL + ALT + 5
} else if(M3 == glowing){
   G1 = CTRL + ALT + F1
   G2 = CTRL + ALT + F2
   G3 = CTRL + ALT + F3
   G4 = CTRL + ALT + F4
   G5 = CTRL + ALT + F5
}
```

**Comment by pfps** [comment]
You should be able to do this using the current version of Solaar in this repository.

There does not appear to be a way of accessing the current state of the lights.  Instead you have to arrange for Solaar to control the lights.

First, divert the G-keys (which also diverts the M and MR keys).

Then write rules to use the M-keys to control their lights, something like
```
---
- Key: [M1, pressed]
- Set: [m-key-leds, M1, true]
- Set: [m-key-leds, M2, false]
- Set: [m-key-leds, M3, false]
...
```
and rules to do things with the G-keys, something like
```
---
- Key: [G1, pressed]
- Setting: [m-key-leds, M1, true]
- Execute: [notify-send, 'G1 pressed when M1 lit']
...
```

**Comment by Svenum** [comment]
I think you miss understand me.
I fought you can read the current state of the LED because of the toggle Options.

I have done that already:
```
---
- Key: [M1, pressed]
- Set: [m-key-leds, M1, true]
- Set: [m-key-leds, M2, false]
- Set: [m-key-leds, M3, false]
...
```
If you are able to check the state of the LED you are able to create three different "profiles" for the G-Keys for example.
That is what the M-Keys official for.
I mean something like this.
```
---
- Rule:
   - Test: [m-key-leds, M1, true]
   - AND
   - Key: [G1, pressed]
   - KeyPress: [Control_R, Alt_L, Shift_R, F1]
- Rule:
   - Test: [m-key-leds, M2, true]
   - AND
   - Key: [G2, pressed]
   - KeyPress: [Control_R, Alt_L, Shift_R, A]
...
```

**Comment by pfps** [comment]
The problem with 
```
   - Test: [m-key-leds, M1, true]
```
is that Test tests against the current notification, which would be the pressing of a G key.  To test whether an LED is lit (actually whether Solaar thinks an LED is lit) you need to test the state of a Solaar setting, which is done by a Setting: condition such as
```
- Setting: [m-key-leds, M1, true]
```

**Comment by Svenum** [comment]
Maybe is test the false option but you should be able to check this maybe with a switch-case:
![image](https://user-images.githubusercontent.com/43136984/158055839-e5cbe1e4-f81c-4a93-a5d3-05dbad975bef.png)

And if this is posible it is posible to add a new condition like CheckState or something like that.

**Comment by pfps** [comment]
That's what Setting does.

**Comment by pfps** [comment]
Oops, I forgot the first argument of Setting, which is either null or the serial number of a device.   So you need to add null as the first argument of all the Setting conditions above.

**Comment by Svenum** [comment]
Is this Setting-Condition accessible via gui?

**Comment by Svenum** [comment]
Ok, thank you,
 that works but i can not access the Setting-Condition via GUI, right?

```
---
- Rule:
  - Key: [M1, pressed]
  - Set:
    - null
    - m-key-leds
    - 1
    - true
  - Set:
    - null
    - m-key-leds
    - 2
    - false
  - Set:
    - null
    - m-key-leds
    - 4
    - false
- Rule:
  - Key: [M3, pressed]
  - Set:
    - null
    - m-key-leds
    - 4
    - true
  - Set:
    - null
    - m-key-leds
    - 2
    - false
  - Set:
    - null
    - m-key-leds
    - 1
    - false
- Rule:
  - Key: [M2, pressed]
  - Set:
    - null
    - m-key-leds
    - 2
    - true
  - Set:
    - null
    - m-key-leds
    - 1
    - false
  - Set:
    - null
    - m-key-leds
    - 4
    - false
...
---
- Rule:
  - Key: [G1, pressed]
  - Setting: [null, m-key-leds, M1, true]
  - KeyPress: [Control_R, Alt_L, Shift_R, F1]
- Rule:
  - Key: [G2, pressed]
  - Setting: [null, m-key-leds, M1, true]
  - KeyPress: [Control_R, Alt_L, Shift_R, F2]
- Rule:
  - Key: [G3, pressed]
  - Setting: [null, m-key-leds, M1, true]
  - KeyPress: [Control_R, Alt_L, Shift_R, F3]
- Rule:
  - Key: [G4, pressed]
  - Setting: [null, m-key-leds, M1, true]
  - KeyPress: [Control_R, Alt_L, Shift_R, F4]
- Rule:
  - Key: [G5, pressed]
  - Setting: [null, m-key-leds, M1, true]
  - KeyPress: [Control_R, Alt_L, Shift_R, F5]
...
```
