### ISSUE TITLE
Add rule component to sleep for a while

### ISSUE THREAD

**Issue by tosilswc** [pwr-Solaar/Solaar#1770]
It is possible to add a sleep action in the rule editor so we can perform keystrokes after a program has loaded?
(e.g. I load google docs from terminal opening chrome on a specific document, I wait 5 seconds so google docs loads correctly and then I invoke a key press for activating speech recognition).

**Comment by pfps** [comment]
It is possible.  The issue is just what the sleep action does.
The simplest design is to have sleep take two arguments - a delay and a rule to run after the delay.  This decouples processing of subsequent rule pieces and other rules from the processing of the slept part of the rule.
So you would have a rule something like:
```
---
- MouseGesture: [Mouse Gesture Button, Mouse Right]
- Execute: [docs]
- Sleep:
  - 5.5
  - Rule:
    - KeyPress:
      - [whatever key is needed to start speech recognition]
      - click
- Execute: [notify-send, Starting speech recognition in 5.5 seconds]
...
```
This design makes it easy to set up the sleep and the processing after the sleep.

**Comment by pfps** [comment]
PR #1771 adds a later action.  I'm using Later, as Sleep isn't the best name fo this action.  I'm open to a different name.

Later takes an *integer* delay in seconds and several rule components, as in
```
---
- MouseGesture: [Mouse Gesture Button, Mouse Right]
- Execute: [notify-send, Executing Later]
- Later:
  - 5
  - Execute: [notify-send, Executed Later]
  - Execute: [notify-send, Executed Later 2]
- Execute: [notify-send, Now]
...
```
You have to modify `~/.config/Solaar/rules.yaml` as there is no support in the rule editor yet.



To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #1771, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/1771/head:pull_1771
git checkout pull_1771
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_1771
git fetch origin pull/1771/head
git reset --hard FETCH_HEAD
```
