### ISSUE TITLE
Rules negate did not work

### ISSUE THREAD

**Issue by phpcitizen** [pwr-Solaar/Solaar#1817]
- Solaar version: 1.1.5
- Distribution: Nixos
- Kernel version: `5.16.11`

**Describe the bug**
Negate (NOT) feature in rules does not seem to be working.

**To Reproduce**
Negate an Active Keyboard condition. (If the keyboard is not active, in my understanding)
From actions: Set Mouse host to another host.

**Comment by pfps** [comment]
Please provide the rule that is not working correctly.

**Comment by pfps** [comment]
This rule works as expected when the mouse 198E3EB8 is off and the keyboard 43DAF041 is on.   Only two notifications are sent.

```
---
- Key: [Host Switch Channel 2, released]
- Rule:
  - Active: 198E3EB8
  - Set: [43DAF041, change-host, 1]
  - Set: [198E3EB8, change-host, 1]
  - Execute: [notify-send, Switched keyboard and mouse to idefix]
- Execute: [notify-send, Mouse not active]
- Not:
    Active: 198E3EB8
- Execute: [notify-send, mna 2]
- Not:
    Active: 43DAF041
- Execute: [notify-send, mna 3]
- Set: [43DAF041, change-host, 1]
- Execute: [notify-send, Switched keyboard to idefix. Mouse not active, it will have
      to be switched manually]
...
```
