### ISSUE TITLE
Newbie Question: Can I use MX Keys/Anywhere3 with a Windows and a Linux computer using Solaar?

### ISSUE THREAD

**Issue by archfrog** [pwr-Solaar/Solaar#1929]
I own an `MX Keys` keyboard and an `MX Anywhere 3` mouse that I've been using exclusively on Windows (without any pairing on my part).

Yesterday I set up a new Linux box, which shares the monitor with the Windows box, and now I want to use the keyboard and mouse on this new box as well, hopefully without having to move the Unifying Receivers between the two PCs all the time.

I have some vague notion that it should be possible to switch the keyboard and mouse between Windows and Linux just by pressing one of the special device selector keys (`1`, `2`, `3` keys on the `MX Keys` keyboard, the keys just above `Insert`/`Home`/`Page Up`).

I am not at all sure that this is possible at all.  And if it is possible, if it is possible using Solaar.  

My platforms are Windows 10 Pro x64 and Ubuntu Desktop 22.10 x64.  I used [Issue 1245](https://github.com/pwr-Solaar/Solaar/issues/1245) to install Solaar on Ubuntu and Solaar appears to work well.

I am not expecting a detailed walk-through of how to accomplish this, more of a quick reply like "yes, it can easily be done" or "no, it cannot be done" (any hint and tips are welcome, though).  I've been experimenting and reading for about two hours with no luck so far.  I still have to move the receivers :-)

It would be so sexy if I could switch keyboard and mouse forth and back between Windows and Linux just with a keypress :-)

**Comment by pfps** [comment]
Solaar makes it possible (using rules) to switch multiple devices when a host switching key is pressed.  You need to use Solaar to divert one of the host switching keys and have a rule that triggers on the key release and switches the keyboard and mouse to a different host.

Here are two rules that perform switching of a keyboard and mouse, by identifier.  The first pops up a notification if the mouse is not active and can't be switched.  More information on Solaar rules can be found in https://pwr-solaar.github.io/Solaar/rules


```
---
- Key: [Host Switch Channel 2, released]
- Rule:
  - Active: 198E3EB8
  - Set: [43DAF041, change-host, 1]
  - Set: [198E3EB8, change-host, 1]
  - Execute: [notify-send, Switched keyboard and mouse to idefix]
- Set: [43DAF041, change-host, 1]
- Execute: [notify-send, Switched keyboard to idefix. Mouse not active, it will have
      to be switched manually]
...
---
- Key: [Host Switch Channel 3, released]
- Set: [43DAF041, change-host, 2]
- Set: [198E3EB8, change-host, 2]
- Execute: [notify-send, Switched to other]
...
```
