### ISSUE TITLE
Correct rules.yaml for Logitech MX Master 3S

### ISSUE THREAD

**Issue by charlesalec** [pwr-Solaar/Solaar#2020]
Information

    Solaar version (solaar --version and git describe --tags): 1.1.8
    Distribution: Ubuntu 20.04.01
    Kernel version (ex. uname -srmo): Linux 5.19.0-35-generic x86_64 GNU/Linux

Does anyone have a proper .yaml file + solaar options screenshot that properly configures the MX Master 3S forward and backward thumb buttons, as well as the mouse wheel press button? 
I am having issues with configuring:
- the thumb up and down buttons to go forward/backward on browsers, etc...
- scroll button press closes tabs
I would be extremely grateful if anyone has been able to configure it how it works on other operating systems.

All the best

**Comment by charlesalec** [comment]
Found out the issue, closing.

**Comment by pfps** [comment]
It would be useful to say what you did so that others who might have this problem can learn from your experiences.

**Comment by charlesalec** [comment]
See below for the rules.yaml and config.yaml that effectively make the mouse behave exactly the same as with Windows and Mac:

rules.yaml
`%YAML 1.3
---
- Rule:
  - MouseGesture: Mouse Right
  - KeyPress:
    - [Super_L, Page_Down]
    - click
- Rule:
  - MouseGesture: Mouse Left
  - KeyPress:
    - [Super_L, Page_Up]
    - click
- Rule:
  - MouseGesture: Mouse Up
  - KeyPress:
    - [Super_L, a]
    - click
- Rule:
  - MouseGesture: Mouse Down
  - KeyPress:
    - [Super_L, d]
    - click
- Rule:
  - And:
    - Key: [Mouse Gesture Button, released]
    - MouseGesture: []
  - KeyPress:
    - [Super_L, s]
    - click
...
---`

config.yaml:
`- 1.1.8
- _NAME: MX Keys Keyboard
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, pointer_speed, dpi, speed-change, backlight-timed, reprogrammable-keys, persistent-remappable-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer]
  _battery: 4096
  _modelId: B35B408A0000
  _serial: 80AA0ACC
  _unitId: 80AA0ACC
  _wpid: 408A
  backlight: true
  change-host: null
  disable-keyboard-keys: {1: false, 2: false, 4: false, 8: false, 16: false}
  divert-keys: {10: 0, 110: 0, 111: 0, 191: 0, 199: 0, 200: 0, 209: 0, 210: 0, 211: 0, 224: 0, 225: 0, 226: 0, 227: 0, 228: 0, 229: 0, 230: 0, 231: 0, 232: 0,
    233: 0, 234: 0, 235: 0, 236: 0}
  fn-swap: true
  multiplatform: 0
- _NAME: MX Master 3S
  _absent: [hi-res-scroll, lowres-scroll-mode, onboard_profiles, report_rate, pointer_speed, speed-change, backlight, backlight-timed, fn-swap, persistent-remappable-keys,
    disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params,
    sidetone, equalizer]
  _battery: 4100
  _modelId: B03400000000
  _sensitive: {divert-keys: true, dpi: true, reprogrammable-keys: false, thumb-scroll-invert: true, thumb-scroll-mode: true}
  _serial: 79B31519
  _unitId: 79B31519
  _wpid: B034
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 195: 2, 196: 2}
  dpi: 900
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: false
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 195: 195, 196: 195}
  scroll-ratchet: 2
  smart-shift: 10
  thumb-scroll-invert: false
  thumb-scroll-mode: false`

**Comment by charlesalec** [comment]
For anyone who wishes to have their MX Master 3S behave exactly like in Windows/macOS, use the following for rules.yaml:

```
%YAML 1.3
---
- Rule:
  - MouseGesture: Mouse Right
  - KeyPress:
    - [Super_L, Page_Down]
    - click
- Rule:
  - MouseGesture: Mouse Left
  - KeyPress:
    - [Super_L, Page_Up]
    - click
- Rule:
  - MouseGesture: Mouse Up
  - KeyPress:
    - [Super_L, a]
    - click
- Rule:
  - MouseGesture: Mouse Down
  - KeyPress:
    - [Super_L, d]
    - click
- Rule:
  - And:
    - Key: [Mouse Gesture Button, released]
    - MouseGesture: []
  - KeyPress:
    - [Super_L, s]
    - click
...
---
```

And the following for the configuration:
Key/button actions: back button -> mouse back button, same for forward and muddle button.
