### ISSUE TITLE
Is mapping the forward/back mouse buttons to combination of keyboard keys doable with Solaar?

### ISSUE THREAD

**Issue by Aqua1ung** [pwr-Solaar/Solaar#2070]
Just so I do not waste my time on learning how to write rules for the Solaar Rule Editor only to find out later that it can't be done, is it possible to map mouse buttons onto keyboard key combinations that switch Workspaces, such as, say, back button mapped to Super + PgDown?

(And yes, both my mouse and keyboard are Logitech.)

**Comment by Aqua1ung** [comment]
Done. Here goes `rules.yaml`:
```
%YAML 1.3
---
- Rule:
  - Key: [Forward Button, pressed]
  - KeyPress:
    - [Super_L, Page_Up]
    - click
- Rule:
  - Key: [Back Button, pressed]
  - KeyPress:
    - [Super_L, Page_Down]
    - click
...
```
