### ISSUE TITLE
default action when rule evaluates to false

### ISSUE THREAD

**Issue by clowergen** [pwr-Solaar/Solaar#2161]
Using the Solaar GUI, I diverted my MX Master 3S's buttons and set them to press some keys when the mouse is in an Audacity window, for example:
```
---
- MouseProcess: audacity.bin
- Rule:
  - Key: [Back Button, pressed]
  - KeyPress:
    - [Control_L, Alt_L, x]
    - click
...
```
This worked.
But when the mouse is _not_ in Audacity, the buttons do nothing. My assumption is Solaar caught the event, went through the rule, found that the condition is not matched, and ignored the rest.
Is this intended behaviour? If so, how can I tell the buttons to do what they are originally meant to do, when the condition is not fulfilled?
I've tried adding a new rule underneath my rule, to tell Solaar to click the back button. But I couldn't find an action that would do that.
