### ISSUE TITLE
How do I map the thumb wheel of my mx master 3 to system volume up/down

### ISSUE THREAD

**Issue by rp1231** [pwr-Solaar/Solaar#2408]
Sorry for creating the issue.
I created the issue as there was no discussions page.

I can't figure out how to remap the thumb scroll wheel to system volume up/down.
Thanks

**Comment by pfps** [comment]
You need to write a Solaar rule that triggers on diverted thumb wheel notifications and then does something to affect the system volume.   The former is similar to one of the rules in the rule documentation page.  The latter will likely be emulating a key press or executing an external program.

**Comment by MattHag** [comment]
You can add this to your configuration YML. Start Solaar and in the rule editor change the keypresses to XF86_volume... or similar.
```
---
- Rule:
  - Test: [thumb_wheel_up, 10]
  - KeyPress:
    - [Control_L, Page_Down]
    - click
...
---
- Rule:
  - Test: [thumb_wheel_down, 10]
  - KeyPress:
    - [Control_L, Page_Up]
    - click
...
```
