### ISSUE TITLE
Switching keyboard AND mouse (as a pair) between computers using only the three Easy-Switch multi-device F-keys

### ISSUE THREAD

**Issue by imfatant** [pwr-Solaar/Solaar#2673]
Just as I was going to pen my own lengthy question about this topic on Stack Exchange's Superuser site (albeit that particular question and its answer implies the use of of strictly official Logitech software), I spotted that someone had already asked the question very succinctly there:

Question and (single) answer on Superuser (dated 2022/2023): https://superuser.com/questions/1703762/sync-logitech-keyboard-and-mouse-connection-when-i-switch-devices

Official answer direct from Logitech: https://support.logi.com/hc/en-us/articles/1500008089162-Can-I-switch-my-mouse-and-keyboard-at-the-same-time-using-one-Easy-Switch-button

So my question here is - perhaps can Solaar help me do this? Or is there a clever workaround? And please note I'm not really talking about the official mouse-based so-called Flow feature here; I'm talking about using the three white Easy-Switch multi-device F-keys on my Logitech K780 keyboard.

This issue has been plaguing me for days, so all information and advice would be GREATLY appreciated.

I should mention that I'd ideally like to be switching between two Raspberry Pi 5 boxes running various flavours of Linux and my main Intel-based Windows 10 desktop computer (each, naturally, equipped with its own Unifying Receiver) which no doubt complicates matters further...

-- Imf

**Comment by pfps** [comment]
This is indeed possible as long as you can divert the keys.  You divert the keys and write Solaar rules that switch the keyboard and mouse.  You have to be running something on the other machine to switch back and maybe the Logitech software has an incompatible solution.  I've never tried with Windows as one of the targets, but I have done this between two Linux boxes.  I haven't had a setup where I wanted to do this for a while so the rules might not be the best for the current version of Solaar.

Here are two versions of the rules that I have used.  The keyboard is a Craft, which has three separate switching keys.  It is important to trigger the rules on key release.

```
- Key: [Host Switch Channel 2, released]
- Rule:
  - Active: 198E3EB8
  - Set: [43DAF041, change-host, 1]
  - Set: [198E3EB8, change-host, 1]
  - Execute: [notify-send, Switched keyboard and mouse to idefix]
- Execute: [notify-send, Mouse not active]
- Set: [43DAF041, change-host, 1]
- Execute: [notify-send, Switched keyboard to idefix. Mouse not active, it will have
      to be switched manually]
...
---
- Key: [Host Switch Channel 3, released]
- Set: [43DAF041, change-host, 2]
- Set: [198E3EB8, change-host, 2]
- Execute: [notify-send, Switched to other]
...
```
